# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hmkim-cluster
  region: ap-northeast-2
availabilityZones: ["ap-northeast-2a", "ap-northeast-2c"]
managedNodeGroups:
- name: spot
  instanceTypes: ["c4.large","c5.large","c5d.large","c5n.large","c5a.large"]
  spot: true
  desiredCapacity: 1
